name: Build

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/build.yml'
      - 'Makefile'
      - 'package.json'
      - 'src/**'
      - 'test/**'
      - 'vitest.config.js'
      - 'wrangler.toml'
      - 'yarn.lock'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: yarn

    - name: Test
      run: yarn test
